Repository MoyeoRun/MoyeoRun_iOS, pull requests merged in 2022-09, with the labels that each got.

#72 [#12]: modify make room design
  MoyeoRun.xcodeproj/project.pbxproj
  MoyeoRun/Assets.xcassets/Main/Contents.json
  MoyeoRun/Assets.xcassets/Main/Image.imageset/Contents.json
  MoyeoRun/Assets.xcassets/Main/Image.imageset/Image.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image-9.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image-9.imageset/Image.png
  MoyeoRun/Data/Main/DTO/CurrentRoomListDTO.swift
  MoyeoRun/Scenes/HomeTab/ViewControllers/HomeTabContainers/HomeTabLastRecordContainer.swift
  MoyeoRun/Scenes/HomeTab/ViewControllers/HomeTabContainers/HomeTabNewMissionContainer.swift
  MoyeoRun/Scenes/HomeTab/ViewControllers/HomeTabContainers/HomeTabNowPopularContainer.swift
  MoyeoRun/Scenes/HomeTab/ViewControllers/HomeTabViewController.swift
  MoyeoRun/Scenes/HomeTab/ViewControllers/HomeViewController.swift
  MoyeoRun/Scenes/HomeTab/Views/Cells/CurrentJoinRoomCell.swift
  MoyeoRun/Scenes/HomeTab/Views/Cells/CurrentRoomListCell.swift
  MoyeoRun/Scenes/HomeTab/Views/Cells/HomeTabLastRecordCell.swift
  MoyeoRun/Scenes/HomeTab/Views/Cells/HomeTabNewMissionCell.swift
  MoyeoRun/Scenes/HomeTab/Views/Cells/HomeTabNowPopularCell.swift
  MoyeoRun/Scenes/HomeTab/Views/Cells/HomeTopCell.swift
  MoyeoRun/Scenes/HomeTab/Views/Cells/RoomHeader.swift
  MoyeoRun/Scenes/HomeTab/Views/Cells/RoomView.swift
  MoyeoRun/Scenes/HomeTab/Views/InterfaceBuilders/CurrentJoinRoomCell.xib
  MoyeoRun/Scenes/HomeTab/Views/InterfaceBuilders/CurrentRoomListCell.xib
  MoyeoRun/Scenes/HomeTab/Views/InterfaceBuilders/HomeTab.storyboard
  MoyeoRun/Scenes/HomeTab/Views/InterfaceBuilders/HomeTopCell.xib
  MoyeoRun/Scenes/HomeTab/Views/InterfaceBuilders/Room.xib
  MoyeoRun/Scenes/HomeTab/Views/InterfaceBuilders/RoomHeader.xib
  MoyeoRun/Scenes/Login/ViewControllers/AppIntroViewController.swift
  MoyeoRun/Scenes/Login/ViewControllers/InsertUserInfoViewController.swift
  MoyeoRun/Scenes/Login/ViewControllers/ProfileImageMenuViewController.swift
  MoyeoRun/Scenes/Login/ViewControllers/SignUpCompleteViewController.swift
  MoyeoRun/Scenes/Login/ViewControllers/SocialLogInViewController.swift
  MoyeoRun/Scenes/Login/Views/InterfaceBuilders/AppIntro.storyboard
  MoyeoRun/Scenes/Login/Views/InterfaceBuilders/InsertUserInfo.storyboard
  MoyeoRun/Scenes/Login/Views/InterfaceBuilders/ProfileImageMenu.storyboard
  MoyeoRun/Scenes/Login/Views/InterfaceBuilders/SignUpComplete.storyboard
  MoyeoRun/Scenes/Login/Views/InterfaceBuilders/SocialLogIn.storyboard
  MoyeoRun/Scenes/Main/Views/InterfaceBuilders/MainPopupView.storyboard
  MoyeoRun/Scenes/MakeRoom/MakeRoomController.swift
  MoyeoRun/Scenes/MakeRoom/ViewControllers/MakeRoomController.swift
  MoyeoRun/Scenes/MakeRoom/ViewControllers/PopupViewController.swift
  MoyeoRun/Scenes/MakeRoom/ViewControllers/SelectPhotoController.swift
  MoyeoRun/Scenes/MakeRoom/ViewControllers/StartTimePopUpViewController.swift
  MoyeoRun/Scenes/MakeRoom/Views/Cells/PhotoCell.swift
  MoyeoRun/Scenes/MakeRoom/Views/InterfaceBuilders/MakeRoom.storyboard
  MoyeoRun/Scenes/MakeRoom/Views/InterfaceBuilders/SelectPhoto.storyboard
  MoyeoRun/Scenes/MakeRoom/Views/PopupViewController.swift
  MoyeoRun/Scenes/MoyeorunRoom/Views/InterfaceBuilders/MoyeoRunRoom.storyboard
  MoyeoRun/Scenes/TabBar/ViewControllers/Extensions.swift
  MoyeoRun/Util/Designable/UIView+.swift
Labels: refactor

#74 [#13]: modify moyeorun room design
  MoyeoRun.xcodeproj/project.pbxproj
  MoyeoRun/Assets.xcassets/MoyeorunRoom/bluePeople.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MoyeorunRoom/bluePeople.imageset/Image.png
  MoyeoRun/Assets.xcassets/MoyeorunRoom/paceImg.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MoyeorunRoom/paceImg.imageset/Image.png
  MoyeoRun/Assets.xcassets/MoyeorunRoom/runCharacter.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MoyeorunRoom/runCharacter.imageset/Image.png
  MoyeoRun/Scenes/MoyeorunRoom/RoomController.swift
  MoyeoRun/Scenes/MoyeorunRoom/Views/InterfaceBuilders/AfterRoom.xib
  MoyeoRun/Scenes/MoyeorunRoom/Views/InterfaceBuilders/BeforeRoom.xib
  MoyeoRun/Scenes/MoyeorunRoom/Views/InterfaceBuilders/MoyeoRunRoom.storyboard
  MoyeoRun/Scenes/MoyeorunRoom/Views/InterfaceBuilders/Room.storyboard
  Podfile.lock
Labels: style

#75 기록 페이지 디자인 수정 반영
  MoyeoRun.xcodeproj/project.pbxproj
  MoyeoRun/Assets.xcassets/Util/calendar.imageset/Contents.json
  MoyeoRun/Assets.xcassets/Util/calendar.imageset/calendar.png
  MoyeoRun/Assets.xcassets/Util/calendar.imageset/calendar2.png
  MoyeoRun/Assets.xcassets/Util/calendar.imageset/calendar3.png
  MoyeoRun/Scenes/RecordTab/ViewControllers/CalendarViewController.swift
  MoyeoRun/Scenes/RecordTab/ViewControllers/DatePickerViewController.swift
  MoyeoRun/Scenes/RecordTab/ViewControllers/RecordTabViewController.swift
  MoyeoRun/Scenes/RecordTab/Views/InterfaceBuilders/DatePicker.storyboard
  MoyeoRun/Scenes/RecordTab/Views/InterfaceBuilders/RecordTab.storyboard
  Podfile
  Podfile.lock
Labels: refactor, style
