Repository MoyeoRun/MoyeoRun_iOS, pull requests merged in 2022-03, with the labels that each got.

#14 [#1]: Conventional Commits 스타일 적용
  .pre-commit-config.yaml
Labels: style

#15 [#2]: auto-assign 설정
  .github/auto-assign.yml
Labels: chore

#16 [#6]: 프로젝트에 Cocoapods 설치
  MoyeoRun.xcodeproj/project.pbxproj
  MoyeoRun.xcworkspace/contents.xcworkspacedata
  MoyeoRun.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Podfile
  Podfile.lock
Labels: build

#19 [#7] SwiftLint 적용
  .swiftlint.yml
  MoyeoRun.xcodeproj/project.pbxproj
  MoyeoRun/AppDelegate.swift
  MoyeoRun/SceneDelegate.swift
  MoyeoRun/ViewController.swift
  Podfile
  Podfile.lock
Labels: build

#20 [#9]: Development Target 설정
  MoyeoRun.xcodeproj/project.pbxproj
Labels: build

#21 [#8]: pull request template 적용
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#25 [#8]: pull request template 적용
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#24 style: folder structure
  .DS_Store
  MoyeoRun.xcodeproj/project.pbxproj
  MoyeoRun/.DS_Store
  MoyeoRun/LifeCycles/AppDelegate.swift
  MoyeoRun/LifeCycles/SceneDelegate.swift
Labels: style

#27 chore: gitignore 추가
  .DS_Store
  .gitignore
  MoyeoRun/.DS_Store
  Podfile.lock
Labels: chore

#30 chore: remove .DS_Store
  .DS_Store
  MoyeoRun/.DS_Store
Labels: chore

#32 [#10]: make room storyboard
  MoyeoRun.xcodeproj/project.pbxproj
  MoyeoRun/Scenes/MakeRoom/Views/InterfaceBuilders/MakeRoom.storyboard
Labels: style

#38 [#37]: 사용자 위치 권한 설정 추가
  MoyeoRun/Info.plist
Labels: docs
