Repository MoyeoRun/MoyeoRun_iOS, pull requests merged in 2022-05, with the labels that each got.

#57 [#56]: 로그인 기본정보 입력 화면 작업
  MoyeoRun.xcodeproj/project.pbxproj
  MoyeoRun/Assets.xcassets/Colors/BorderColor1.colorset/Contents.json
  MoyeoRun/Assets.xcassets/LogIn/Female.imageset/Contents.json
  MoyeoRun/Assets.xcassets/LogIn/Female.imageset/성별여.png
  MoyeoRun/Assets.xcassets/LogIn/Male.imageset/Contents.json
  MoyeoRun/Assets.xcassets/LogIn/Male.imageset/성별남.png
  MoyeoRun/Assets.xcassets/LogIn/Welcome image.imageset/Contents.json
  MoyeoRun/Assets.xcassets/LogIn/Welcome image.imageset/Welcome image.png
  MoyeoRun/Scenes/HomeTab/Views/InterfaceBuilders/HomeTab.storyboard
  MoyeoRun/Scenes/LogIn/ViewControllers/AppIntroViewController.swift
  MoyeoRun/Scenes/LogIn/ViewControllers/InsertUserInfoViewController.swift
  MoyeoRun/Scenes/LogIn/ViewControllers/ProfileImageMenuViewController.swift
  MoyeoRun/Scenes/LogIn/ViewControllers/SignUpCompleteViewController.swift
  MoyeoRun/Scenes/LogIn/ViewControllers/SocialLogInViewController.swift
  MoyeoRun/Scenes/LogIn/Views/InterfaceBuilders/AppIntro.storyboard
  MoyeoRun/Scenes/LogIn/Views/InterfaceBuilders/InsertUserInfo.storyboard
  MoyeoRun/Scenes/LogIn/Views/InterfaceBuilders/ProfileImageMenu.storyboard
  MoyeoRun/Scenes/LogIn/Views/InterfaceBuilders/SignUpComplete.storyboard
  MoyeoRun/Scenes/LogIn/Views/InterfaceBuilders/SocialLogIn.storyboard
  MoyeoRun/Scenes/MoyeorunRoom/Views/InterfaceBuilders/MoyeoRunRoom.storyboard
  Podfile
  Podfile.lock
Labels: feat

#53 [#3]: 모여런 방 디자인 변경 적용
  MoyeoRun.xcodeproj/xcshareddata/xcschemes/MoyeoRun.xcscheme
  MoyeoRun/Assets.xcassets/MakeRoom/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallery.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallery.imageset/Group 228.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Image-1.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Image-1.imageset/Image.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Image-2.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Image-2.imageset/Image.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Image-3.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Image-3.imageset/Image.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Image-4.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Image-4.imageset/Image.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Image-5.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Image-5.imageset/Image.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Image-6.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Image-6.imageset/Image.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Image-7.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Image-7.imageset/Image.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Image-8.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Image-8.imageset/Image.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Image.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Image.imageset/Image.png
  MoyeoRun/Scenes/Main/Views/InterfaceBuilders/MainPopupView.storyboard
  MoyeoRun/Scenes/MakeRoom/Views/InterfaceBuilders/MakeRoom.storyboard
Labels: style

#52 [#11]: make room design modify
  MoyeoRun.xcodeproj/project.pbxproj
  MoyeoRun/Scenes/MakeRoom/Views/InterfaceBuilders/MakeRoom.storyboard
Labels: style

#55 [#4]: 모여런 방만들기 배경 이미지 선택
  MoyeoRun.xcodeproj/project.pbxproj
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image-1.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image-1.imageset/Image.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image-2.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image-2.imageset/Image.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image-3.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image-3.imageset/Image.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image-4.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image-4.imageset/Image.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image-5.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image-5.imageset/Image.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image-6.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image-6.imageset/Image.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image-7.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image-7.imageset/Image.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image-8.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image-8.imageset/Image.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image.imageset/Contents.json
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/Image.imageset/Image.png
  MoyeoRun/Assets.xcassets/MakeRoom/gallerySet/gallerySet/Contents.json
  MoyeoRun/Scenes/MakeRoom/Views/InterfaceBuilders/SelectPhoto.storyboard
  MoyeoRun/Scenes/MakeRoom/Views/PhotoCell.swift
  MoyeoRun/Scenes/MakeRoom/Views/SelectPhotoController.swift
Labels: feat

#60 [#17]: Data 레이어 API 통신 로직 추가
  .gitignore
  Configuration/Configuation.swift
  MoyeoRun.xcodeproj/project.pbxproj
  MoyeoRun/Data/Auth/DTO/AuthDTO.swift
  MoyeoRun/Data/Auth/DTO/LogoutDTO.swift
  MoyeoRun/Data/Auth/DTO/RefreshDTO.swift
  MoyeoRun/Data/Auth/DTO/SignInDTO.swift
  MoyeoRun/Data/Auth/DTO/SignUpDTO.swift
  MoyeoRun/Data/Auth/DataSource/AuthLocalDataSource.swift
  MoyeoRun/Data/Auth/DataSource/AuthRemoteDataSource.swift
  MoyeoRun/Data/Auth/Repository/AuthRepository.swift
  MoyeoRun/Data/Base/Keychain/Keychain.swift
  MoyeoRun/Data/Base/Keychain/KeychainKeyType.swift
  MoyeoRun/Data/Base/Keychain/KeychainStore.swift
  MoyeoRun/Data/Base/Network/MoyaProvider+.swift
  MoyeoRun/Data/Base/Network/Response.swift
  MoyeoRun/Data/Base/Network/TargetType+.swift
  MoyeoRun/Data/User/DTO/DuplicateDTO.swift
  MoyeoRun/Data/User/DTO/UserDTO.swift
  MoyeoRun/Data/User/DataSource/UserRemoteDataSource.swift
  MoyeoRun/Data/User/Repository/UserRepository.swift
  MoyeoRun/Info.plist
  Podfile
  Podfile.lock
Labels: feat, build
